language: python
cache: pip
python:
  - '3.5'
  - '3.6'
dist: trusty
sudo: false
env:
  - PIP_NO_BINARY=psycopg2
install:
  - pip install pipenv
  - pipenv install --system
script:
  - python manage.py check
  - python manage.py test
