language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
dist: trusty
sudo: false
install: "pip install -r requirements.txt"
script:
  - "python manage.py check"
  - "python manage.py migrate"
  - "python manage.py test"
