language: python
cache: pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
sudo: false
install:
  - "pip install pipenv"
  - "pipenv install --system"
script:
  - "python manage.py check"
  - "python manage.py test"
